# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kaggle-loan-approval-service
spec:
  selector:
    app: kaggle-loan-approval
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
